Select Eligible_Flexi_Amount,EligibleForFL,Loancycle,EligibleLoanAmount,Comments,* From Clients with (NoLock) 
where ClientID='24:31:76:01:05'
Select Clientid, ProductCategory, DateStamp, * from CreditWorthinesstrn with (nolock) where clientid='24:31:76:01:05'
Select Clientid,Datestamp,Coborrower,CoborrowerRelation, * from KYC with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from CreditWorthinesstrnFlexi with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ClientDetail with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_FlexiExpense with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_FlexiHHincome with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ClientDetail with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ClientDetailNext with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ClientHusbandIncome with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ChildrenStaywith1 with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ChildrenStaywith2 with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_ChildrenNotStaywith with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_CCRDetail1 with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_CCRDetail1Next with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_CCRDetail2 with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_CHIPPIDetail with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from LoanAppraisal_InsuranceDetail with (nolock) where clientid='24:31:76:01:05'
Select DateStamp,* from CreditNeedAssessmenttrn with (nolock) where clientid='24:31:76:01:05'
select DateStamp,* from EnqueryStatus with (nolock) where clientid='24:31:76:01:05'
select 'Kyc_conf' as Kyc_conf,* from kyc_conf where clientid='24:31:76:01:05'
select 'IndusInddocument' as IndusInddocument,* from IndusInddocument where clientid='24:31:76:01:05'
select StatusRemark,* from KycVerificationTRN where clientid='24:31:76:01:05'
select CBREnquiry,ApprovalRemarks, TRNLoanid, BMID, LoanAmountBM, LoanAmountApproved, FinalreviewDate, principaloutstanding, * from ClientLoanproposal with (Nolock)
where Clientid='24:31:76:01:05'
Select ClientLoan2UpFrontFee,ClientLoan1UpFrontFee,ClientLoan2InstallmentNumber,ClientLoan1TotalCollected,ClientLoan1AmtDueDisbursed,ClientLoan1AmountDisbursed,* 
From cds2 With (NoLock) Where ClientID='24:31:76:01:05'
Select * from CDS3 With (NoLock) Where ClientID = '24:31:76:01:05'
